name: Radio

on:
  workflow_dispatch:

jobs:
  run-radio:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Liquidsoap (via Docker)
        run: |
          docker run --rm -v ${{ github.workspace }}:/app savonet/liquidsoap liquidsoap /app/radio.liq
